environment       = "production"
db_instance_class = "db.t4g.micro"
server_image      = "396199429035.dkr.ecr.us-east-1.amazonaws.com/highland-oak-tree/server:latest"
client_image      = "396199429035.dkr.ecr.us-east-1.amazonaws.com/highland-oak-tree/client:latest"
domain_name       = "thehighlandoaktree.org"
